mysql:
  host: "127.0.0.1"
  port: 3306
  user: "myadmin"
  password: "myadmin123"
  database: "myadmin"

redis:
  host: 127.0.0.1
  port: 6379
  db: 0
  poolsize: 10
  password:

mongo:
  host: 127.0.0.1
  port: 27017
  username:
  password:
  database: 'yx-d2c'